# Generated by Django 4.1rc1 on 2022-07-25 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="staff",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="staffruleshift",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rosters.shift",
            ),
        ),
        migrations.AddField(
            model_name="staffruleshift",
            name="staffrule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.staffrule"
            ),
        ),
        migrations.AddField(
            model_name="staffrule",
            name="daygroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rosters.daygroup",
            ),
        ),
        migrations.AddField(
            model_name="staffrule",
            name="shifts",
            field=models.ManyToManyField(
                through="rosters.StaffRuleShift", to="rosters.shift"
            ),
        ),
        migrations.AddField(
            model_name="staffrule",
            name="staff",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.shift"
            ),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="shiftrulerole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.role"
            ),
        ),
        migrations.AddField(
            model_name="shiftrulerole",
            name="shiftrule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.shiftrule"
            ),
        ),
        migrations.AddField(
            model_name="shiftrule",
            name="roles",
            field=models.ManyToManyField(
                through="rosters.ShiftRuleRole", to="rosters.role"
            ),
        ),
        migrations.AddField(
            model_name="shiftrule",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.shift"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="daygroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rosters.daygroup",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="daygroupday",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.day"
            ),
        ),
        migrations.AddField(
            model_name="daygroupday",
            name="daygroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rosters.daygroup"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="daygroupday",
            unique_together={("daygroup", "day")},
        ),
    ]
